# FROM run:v1 - you can also refer to the earlier image created in RUN instruction
# # RUN dnf install nginx -y
# CMD ["nginx", "-g", "daemon off;"]
FROM almalinux:9
RUN dnf install nginx -y
CMD ["nginx", "-g", "daemon off;"]